apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: resiliency-components
  
scopes:
  - product-service

spec:
  policies:

    retries:
      infiniteRetries:
        policy: constant
        duration: 5s
        maxRetries: -1 

    circuitBreakers:
      simpleCB:
        maxRequests: 1
        timeout: 5s
        trip: consecutiveFailures >= 5

  targets:
    components:
      statestore:
        outbound:
          retry: infiniteRetries
          circuitBreaker: simpleCB